service: aws-lambda-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cloudfront:*
          Resource: '*'
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: 'arn:aws:lambda:*:*:*'
        - Effect: Allow
          Action:
            - sns:*
          Resource: '*'
        - Effect: Allow
          Action:
            - ses:*
          Resource: 'arn:aws:ses:us-east-1:*:*'
        - Effect: Allow
          Action:
            - secretsmanager:*
          Resource: 'arn:aws:secretsmanager:#{AWS::Region}:#{AWS::AccountId}:secret:*'
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: 'arn:aws:sqs:*:*:*' 



functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: "/saludo/:id"
          method: get
          cors: true
  getCustomers:
    handler: customer.getCustomers
    events:
      - http:
          path: "/customers"
          method: get
          cors: true

  postCustomers:
    handler: customer.postCustomers
    events:
      - http:
          path: "/customers"
          method: post
          cors: true



plugins:
  - serverless-offline
